### PR TITLE
Added updated fields for go to pose

### PR DESCRIPTION
**Pull request by kohlerj**
addresses #62

### CODE REVIEW

**Comment by kohlerj** [comment]
Still WIP

**Comment by kohlerj** [comment]
@mfaessle : somehow when I start there is an offset btw the reference shown in the reference table and the go to fields that I update. This does not happen afterwards when i move around. Any idea why? Is that because you move the point further than it should during the start?

**Comment by mfaessle** [comment]
This is due to the breaking state. Breaking is implemented by keeping the current reference state and wait until the velocity is close to zero and then switch to hover (including an update of the reference state). However since this update of the reference step and the switch to the autopilot's hover state happens simultaneously and in your code you only update the gui if the autopilot is not in hover, the last reference state update is not captured in your code anymore. Maybe you can implement something that detects when the state switches to hover and then do one more update...

**Comment by kohlerj** [comment]
@mfaessle Can we merge this?
@rpg-jenkins test this please

**Pull request merged**
